# Generated by Django 2.1 on 2019-01-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20181231_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
