# Generated by Django 2.1 on 2019-01-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_wish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='card',
        ),
        migrations.AddField(
            model_name='wish',
            name='cards',
            field=models.ManyToManyField(to='cards.Card'),
        ),
    ]
