# Generated by Django 2.1 on 2019-01-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20190101_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
