# Generated by Django 2.1 on 2019-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_card_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-time_stamp']},
        ),
        migrations.AlterField(
            model_name='wish',
            name='cards',
            field=models.ManyToManyField(blank=True, null=True, to='cards.Card'),
        ),
    ]
