# Generated by Django 2.1 on 2019-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20190102_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='cards',
            field=models.ManyToManyField(to='cards.Card'),
        ),
    ]
