# Generated by Django 2.1 on 2019-01-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20190102_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='url',
            new_name='link',
        ),
    ]
